import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useEffect } from 'react'
import Link from 'next/link'
import {
  GetServerSideProps,
  GetStaticPathsContext,
  GetStaticProps,
  NextPage,
} from 'next'
import { getAllData, Product } from '@/types'
import Info from '@/components/Info'
import Data from '@/components/Data'
import Footer from '@/components/Footer'
import Talk from '@/components/Talk'
import Store from '@/components/Store'

export default function Home({ products }: { products: Product[] }) {
  // const addPro = Store((state:any)=>state.getAllProd)
  // const changeVlu = Store((state:any)=>state.optionValuef)
  // useEffect(() => {
  //   addPro(products)
  // }, [changeVlu])
  // console.log('hiya ', changeVlu)

  // const [data, setdata] = useState(product)

  return (
    <>
      <Head>
        <title>E-coo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="stylesheet"
          href="https://use.use.fontawesome.com/releases/v5.0.8/css/all.css"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Info />
        <Data products={products} />
        <Talk />
        <Footer />
      </div>
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async () => {
  const res = await fetch('https://dummyjson.com/products')
  const { products }: getAllData = await res.json()
  console.log(products)

  // console.log('products',products)

  return {
    props: {
      products: products,
    },
  }
}
